In [ ]:
# what is numpy ?
# and why use numpy

# 1. Numpy is a python library
# 2. Numpy is used for scientific computing
# 3. Numpy is fast
# 4. Numpy is efficient
# 5. Numpy is easy to use

# who created numpy ?
# Travis E. Oliphant 2005

In [ ]:
# why use numpy ?

#  in python we have list

#  in numpy we have array
# in numpy array is ndarray

In [ ]:
# why numpy is fast ?
# in numpy array is stored in contiguous memory location

# contiguous memory location
#  Contiguous Memory Allocation :
# Contiguous memory allocation is basically a method in which a single contiguous section/part of memory is allocated to a process or file needing it.

In [ ]:
# which language is numpy written in ?
# python
# java
# c++
# c
# javascript

In [ ]:
pip install numpy

In [ ]:
# import numpy
import numpy as np

In [ ]:
# basic exaample of numpy array
import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# version
print(np.__version__)

1.25.2


In [ ]:
# How to create numpy arrays

# use np.array()



In [ ]:
#  dimension
# 1D
# 2D
# 3D
# 4D
# 5D
# 6D
# 7D
# 8D
# 9D
# 10D


In [ ]:
# 0-d array
# 0-d array , or scalar , are the elements in an array with zero dimensions.

# example
a = np.array(42)
print(a)
print(type(a))

42
<class 'numpy.ndarray'>


In [ ]:
# 1-d array

# example
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 2-d array

a = np.array([[1,2,3],[4,5,6]])


print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3-d array 3x3

A = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A.ndim)


3


In [ ]:
# how to check dimension of array
# use ndim
a = np.array([1,2,3,4,5])
print(a.ndim)

1


In [ ]:
a = np.array([1,2,3,4,5], ndmin = 10)
print(a.ndim)

10


# Numpy Array Indexing

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[4])

1
2
3
4
5


In [ ]:
# sum with indexing

arr = np.array([1,2,3,4,5])

print(arr[0] + arr[1] + arr[2] + arr[3] + arr[4])

15


In [ ]:
# how to access 2-d array

import numpy as np

arr =  np.array([[1,2,3],[4,5,6]])

print(arr)

print("3rd element of 1st row is : " , arr[0,2])

[[1 2 3]
 [4 5 6]]
3rd element of 1st row is :  3


In [ ]:
# how to access 3-d array

import numpy as np

arr  = np.array([[[1,2,3],[4,5,6],[7,8,9]]])




print(arr)

print("3rd element of 1st row is : " , arr[0,1,2])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3rd element of 1st row is :  6


In [ ]:
# nagetive indexing

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[-1])
print(arr[-2])
print(arr[-3])
print(arr[-4])
print(arr[-5])

5
4
3
2
1


# Numpy Array slicing

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[0:3])


[1 2 3]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[2:])


[3 4 5]


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[:3])


[1 2 3]


In [ ]:
# nagetive slicing

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[-3:-1])

[3 4]


In [ ]:
# steps

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[::3])

[1 4]


In [ ]:
# slicing 2-d array

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1,1:4])

[7 8 9]


# Numpy datatypes

In [ ]:
# Numpy datatypes

# int
# float
# complex
# bool
# str

In [ ]:
# reference letter for datatypes

# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode

In [ ]:
# how to check datatype

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr.dtype)

int64


In [ ]:
# string type

import numpy as np

arr = np.array(["apple","banana","cherry"])

print(arr.dtype)

# why output is <u6?
# because string is stored in unicode

<U6


In [ ]:
# creating array with a defined datatype

arr = np.array([1,2,3,4,5], dtype = "float")

print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4. 5.]


In [ ]:

arr = np.array([1,2,3,4,5], dtype = "S")

print(arr.dtype)
print(arr)

|S1
[b'1' b'2' b'3' b'4' b'5']


In [ ]:
# convert datatype

import numpy as np

arr = np.array([1,2,3,4,5])

newarr = arr.astype("float")

strarray  = newarr.astype("S")

print(newarr.dtype)
print(strarray.dtype)

# print(newarr)
# print(newarr.dtype)

float64
|S32


# copy and  view

In [ ]:
# copy
# what is copy in numpy

# copy is another name for view


import numpy as np

arr = np.array([1,2,3,4,5])

x = arr.copy()

arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# view
# make a view , change the original array and display the both arrays

import numpy as np

arr = np.array([1,2,3,4,5])

x = arr.view()

arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


# Numpy array shapes

In [ ]:
# how to check shape of array

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr.shape)

(2, 5)


In [ ]:
# reshaping of an array

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(4,3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# reshape from 1-d to 3

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

newarr = arr.reshape(2,3,2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# flattening an array
# conver multi dimensional array into 1-d array

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

newarr = arr.flatten()

print(newarr)

[ 1  2  3  4  5  6  7  8  9 10]


# Iterating arrays

In [ ]:
import numpy as np

arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [ ]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [ ]:
# iterate each scaler of the 2-d array

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [ ]:
# 3-d array

import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# nditer()

import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# ndenumerate()

import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


# Joining arrays


In [ ]:
# concatenate

import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
# 2-d array

import numpy as np

arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2),axis = 1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# stack function

import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.stack((arr1,arr2),axis = 1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# horizontal stack

import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.hstack((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
# vertical stack

import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.vstack((arr1,arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# dstack

import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.dstack((arr1,arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# SplittiNG ARRAY


In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,6)

print(newarr)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [ ]:
# 2-d array

import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

newarr = np.array_split(arr,3)

print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
# hsplit

import numpy as np


arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

newarr = np.hsplit(arr,3)

print(newarr)

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


# Searching Array

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = np.where(arr == 4)

print(x)

(array([3]),)


In [ ]:
# even number

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [ ]:
# searchsort

# this method called serchsort which performs binary search

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [ ]:
# side

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side = "right")

print(x)

2


In [ ]:
# multiple values

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, [2, 7, 6])

print(x)

[0 1 0]


# Sorted Array

In [ ]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
# alphabetical order

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
# boolean

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [ ]:
# sort multi dimensional array

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# filter array

In [ ]:
# what is filtering an array ?
# Getting some elements out of an existing array and creating a new array out of them

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [ ]:
# creating a filter array

import numpy as np

arr = np.array([41, 42, 43, 44])


filter_arr = []

for element in arr:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [ ]:
# even values

import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])

even = []

for i in arr:
    if i % 2 == 0:
        even.append(True)
    else:
        even.append(False)

newarr = arr[even]

print(newarr)

#

[2 4 6 8]
